#!/usr/bin/env bash
# build.sh -- assemble the Astrocade lobby with zmac.
#
# Usage: ./build.sh
#
# Output: build/lobby.bin, always exactly 8192 bytes: the assembled code,
# zero-padded, mailbox pages clear, "FUJI" claim signature at 0x1CFC so the
# mailbox stays alive when the image is booted over the network. The layout
# contract is enforced by the firmware tree's checkrom.py; tools/checksize.py
# then prints the per-module budget table.
#
# Environment:
#   ENDPOINT=...        lobby /view URL (default https://lobby.fujinet.online/view)
#   PLATFORM=...        platform tag the list is filtered by (default astrocade)
#   DEMO=1              answer every request from a canned room list
#                       (tools/mkdemo.py): no network, for screenshots
#   FUJI_FIRMWARE=path  fujinet-firmware checkout (default ~/Workspace/fujinet-firmware)
#
# zmac is taken from PATH, else ~/Workspace/zmac-1.3, else the copy vendored
# with the cartridge bring-up in fujinet-firmware pico/astrocade.

set -euo pipefail
cd "$(dirname "$0")"

WINDOW=8192
CLAIM_OFF=$((0x1CFC))
ROM_TOP=$((0x1B00))

FUJI_FIRMWARE=${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}
PICO="$FUJI_FIRMWARE/pico/astrocade"

find_zmac() {
    if command -v zmac >/dev/null 2>&1; then
        echo zmac
        return
    fi
    if [ -x "$HOME/Workspace/zmac-1.3/zmac" ]; then
        echo "$HOME/Workspace/zmac-1.3/zmac"
        return
    fi
    local tree="$PICO/tools/zmac"
    if [ ! -d "$tree" ]; then
        echo "build.sh: no zmac on PATH and $tree not found; set FUJI_FIRMWARE" >&2
        exit 1
    fi
    if [ ! -x "$tree/zmac" ]; then
        touch "$tree/zmac.c"    # keep it newer than zmac.y: no yacc wanted
        make -C "$tree" zmac >/dev/null
    fi
    echo "$tree/zmac"
}

ZMAC=$(find_zmac)
mkdir -p build

# Regenerated every run so a stale value cannot survive an environment change.
ENDPOINT="${ENDPOINT:-https://lobby.fujinet.online/view}"
PLATFORM="${PLATFORM:-astrocade}"
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' "$ENDPOINT"
    echo "        DB      0"
    printf 'UPLAT:  DB      "%s"\n' "$PLATFORM"
    echo "        DB      0"
} > build/endpoint.inc

{
    echo "; generated by build.sh -- do not edit"
    echo "DEMO    EQU     ${DEMO:-0}"
} > build/flags.inc
python3 tools/mkdemo.py build/demodata.inc

# zmac 1.3 resolves INCLUDE against the cwd; assemble from here.
"$ZMAC" -o build/lobby.raw -x build/lobby.lst lobby.asm

size=$(wc -c < build/lobby.raw)
if [ "$size" -gt "$ROM_TOP" ]; then
    echo "build.sh: lobby is $size bytes, over the $ROM_TOP ROM top" >&2
    exit 1
fi

# Pad to the full window, clear above ROM_TOP, stamp the claim.
{
    cat build/lobby.raw
    head -c $((WINDOW - size)) /dev/zero
} > build/lobby.bin
printf 'FUJI' | dd of=build/lobby.bin bs=1 seek=$CLAIM_OFF \
    conv=notrunc status=none
rm -f build/lobby.raw

if [ -f "$PICO/tools/checkrom.py" ]; then
    python3 "$PICO/tools/checkrom.py" build/lobby.bin
fi
python3 tools/checksize.py build/lobby.lst
