#!/usr/bin/env python3
"""mkdemo.py -- the DEMO build's canned room list, in /view?bin=1 layout.

Writes build/demodata.inc: DEMON (the record count) and DEMREC, the
records back to back, each exactly as server/model.go serializes one
(189 bytes). Sorted by game, as the server sends them without appkey=.

Usage: mkdemo.py build/demodata.inc
"""

import sys

# (game_type, game, room, server url, client url, players, max)
ROOMS = [
    (1, "5 Card Stud", "Normal", "https://5card.carr-designs.com/?table=n",
     "tnfs://ec.tnfs.io/astrocade/5card.bin", 2, 8),
    (1, "5 Card Stud", "High Rollers", "https://5card.carr-designs.com/?table=h",
     "tnfs://ec.tnfs.io/astrocade/5card.bin", 0, 8),
    (1, "5 Card Stud", "Bots Only", "https://5card.carr-designs.com/?table=b",
     "tnfs://ec.tnfs.io/astrocade/5card.bin", 8, 8),
    (2, "Battleship", "High Seas", "https://battleship.fujinet.online/hs",
     "tnfs://ec.tnfs.io/astrocade/battle.bin", 1, 2),
    (2, "Battleship", "Cape Fuji", "https://battleship.fujinet.online/cf",
     "tnfs://ec.tnfs.io/astrocade/battle.bin", 0, 2),
    (3, "Fujitzee", "Main Room", "https://fujitzee.fujinet.online/main",
     "tnfs://ec.tnfs.io/astrocade/fujitzee.bin", 3, 6),
    (4, "M.U.L.E.", "Planet Irata", "tcp://mule.fujinet.online:6502",
     "tnfs://ec.tnfs.io/astrocade/mule.bin", 1, 4),
    (5, "Texas Hold'em", "Friday Night", "https://holdem.fujinet.online/fri",
     "tnfs://ec.tnfs.io/astrocade/holdem.bin", 4, 8),
    (5, "Texas Hold'em", "AI Table", "https://holdem.fujinet.online/ai",
     "tnfs://ec.tnfs.io/astrocade/holdem.bin", 1, 8),
]


def field(text: str, size: int) -> bytes:
    raw = text.encode("ascii")[: size - 1]
    return raw + bytes(size - len(raw))


def record(gt, game, room, surl, curl, cur, mx) -> bytes:
    rec = (bytes([gt]) + field(game, 17) + field(room, 33) + field(surl, 65)
           + field(curl, 65) + field("us", 3) + bytes([1, cur, mx]) + bytes(2))
    assert len(rec) == 189, len(rec)
    return rec


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    with open(sys.argv[1], "w", encoding="ascii") as f:
        f.write("; generated by tools/mkdemo.py -- do not edit\n")
        f.write(f"DEMON   EQU     {len(ROOMS)}\n")
        f.write("DEMREC:\n")
        for r in ROOMS:
            rec = record(*r)
            f.write(f"; {r[1]} / {r[2]}\n")
            for i in range(0, len(rec), 16):
                f.write("        DB      "
                        + ",".join(f"{b:03X}H" for b in rec[i:i + 16]) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
